# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1205, 803)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-570, -190, 1771, 991))
        self.widget.setStyleSheet("background-color: rgb(93, 8, 116);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(1440, 430, 451, 51))
        self.label.setStyleSheet("font: 33pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(790, 240, 461, 51))
        self.label_2.setStyleSheet("font: 23pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.registerbutt = QtWidgets.QPushButton(self.widget)
        self.registerbutt.setGeometry(QtCore.QRect(720, 770, 471, 61))
        self.registerbutt.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(250, 191, 13);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.registerbutt.setObjectName("registerbutt")
        self.emailfield = QtWidgets.QLineEdit(self.widget)
        self.emailfield.setGeometry(QtCore.QRect(640, 360, 261, 41))
        self.emailfield.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.emailfield.setObjectName("emailfield")
        self.passwordfield = QtWidgets.QLineEdit(self.widget)
        self.passwordfield.setGeometry(QtCore.QRect(640, 440, 261, 41))
        self.passwordfield.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.passwordfield.setObjectName("passwordfield")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(660, 330, 71, 21))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(660, 410, 91, 21))
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.city = QtWidgets.QLineEdit(self.widget)
        self.city.setGeometry(QtCore.QRect(640, 680, 261, 41))
        self.city.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.city.setObjectName("city")
        self.age = QtWidgets.QLineEdit(self.widget)
        self.age.setGeometry(QtCore.QRect(1010, 520, 261, 41))
        self.age.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.age.setObjectName("age")
        self.fname = QtWidgets.QLineEdit(self.widget)
        self.fname.setGeometry(QtCore.QRect(640, 520, 261, 41))
        self.fname.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.fname.setObjectName("fname")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(660, 490, 91, 21))
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(1030, 490, 91, 21))
        self.label_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lname = QtWidgets.QLineEdit(self.widget)
        self.lname.setGeometry(QtCore.QRect(640, 600, 261, 41))
        self.lname.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.lname.setObjectName("lname")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(660, 570, 91, 21))
        self.label_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.country = QtWidgets.QLineEdit(self.widget)
        self.country.setGeometry(QtCore.QRect(1010, 600, 261, 41))
        self.country.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.country.setObjectName("country")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(1030, 570, 91, 21))
        self.label_8.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(660, 650, 91, 21))
        self.label_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.zip = QtWidgets.QLineEdit(self.widget)
        self.zip.setGeometry(QtCore.QRect(1010, 680, 261, 41))
        self.zip.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.zip.setObjectName("zip")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(1030, 650, 91, 21))
        self.label_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.mobile = QtWidgets.QLineEdit(self.widget)
        self.mobile.setGeometry(QtCore.QRect(1010, 360, 261, 41))
        self.mobile.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.mobile.setObjectName("mobile")
        self.gender = QtWidgets.QLineEdit(self.widget)
        self.gender.setGeometry(QtCore.QRect(1010, 440, 261, 41))
        self.gender.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.gender.setObjectName("gender")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(1030, 330, 81, 21))
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(1030, 410, 71, 21))
        self.label_12.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(850, 730, 221, 31))
        self.error.setStyleSheet("font: 16pt \"MS Shell Dlg 2\"; \n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color: rgb(255, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(1330, 500, 451, 51))
        self.label_13.setStyleSheet("font: 33pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label_13.setObjectName("label_13")
        self.gotologpage = QtWidgets.QPushButton(self.widget)
        self.gotologpage.setGeometry(QtCore.QRect(1450, 770, 181, 61))
        self.gotologpage.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(250, 191, 13);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.gotologpage.setObjectName("gotologpage")
        self.done = QtWidgets.QTextEdit(self.widget)
        self.done.setGeometry(QtCore.QRect(1300, 660, 441, 91))
        self.done.setStyleSheet("font: 22pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.done.setObjectName("done")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome"))
        self.label_2.setText(_translate("Dialog", "Create Account For Free"))
        self.registerbutt.setText(_translate("Dialog", "Register"))
        self.label_3.setText(_translate("Dialog", "Email"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.label_5.setText(_translate("Dialog", "First Name"))
        self.label_6.setText(_translate("Dialog", "Age"))
        self.label_7.setText(_translate("Dialog", "Last Name"))
        self.label_8.setText(_translate("Dialog", "country"))
        self.label_9.setText(_translate("Dialog", "city"))
        self.label_10.setText(_translate("Dialog", "Zip Code"))
        self.label_11.setText(_translate("Dialog", "Phone"))
        self.label_12.setText(_translate("Dialog", "Gender"))
        self.label_13.setText(_translate("Dialog", "All You Need Is Here"))
        self.gotologpage.setText(_translate("Dialog", "Continue"))
        self.done.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:26pt;\"><br /></p></body></html>"))
