# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.search = QtWidgets.QLineEdit(Dialog)
        self.search.setGeometry(QtCore.QRect(250, 40, 431, 41))
        self.search.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.search.setObjectName("search")
        self.searchbutt = QtWidgets.QPushButton(Dialog)
        self.searchbutt.setGeometry(QtCore.QRect(720, 40, 161, 41))
        self.searchbutt.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.searchbutt.setObjectName("searchbutt")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(250, 100, 941, 281))
        self.tableWidget.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-21, -1, 221, 811))
        self.widget.setStyleSheet("background-color: rgb(98, 10, 221);")
        self.widget.setObjectName("widget")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(20, 30, 201, 111))
        self.textEdit.setObjectName("textEdit")
        self.submitrate = QtWidgets.QPushButton(self.widget)
        self.submitrate.setGeometry(QtCore.QRect(30, 650, 181, 41))
        self.submitrate.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.submitrate.setObjectName("submitrate")
        self.delivery = QtWidgets.QComboBox(self.widget)
        self.delivery.setGeometry(QtCore.QRect(40, 250, 141, 31))
        self.delivery.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(230, 174, 6);\n"
"background-color: rgb(255, 250, 220);\n"
"background-color: rgb(255, 237, 162);")
        self.delivery.setObjectName("delivery")
        self.delivery.addItem("")
        self.delivery.addItem("")
        self.delivery.addItem("")
        self.delivery.addItem("")
        self.delivery.addItem("")
        self.quality = QtWidgets.QComboBox(self.widget)
        self.quality.setGeometry(QtCore.QRect(40, 340, 141, 31))
        self.quality.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 237, 162);")
        self.quality.setObjectName("quality")
        self.quality.addItem("")
        self.quality.addItem("")
        self.quality.addItem("")
        self.quality.addItem("")
        self.quality.addItem("")
        self.service = QtWidgets.QComboBox(self.widget)
        self.service.setGeometry(QtCore.QRect(40, 430, 141, 31))
        self.service.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 237, 162);")
        self.service.setObjectName("service")
        self.service.addItem("")
        self.service.addItem("")
        self.service.addItem("")
        self.service.addItem("")
        self.service.addItem("")
        self.textEdit_5 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_5.setGeometry(QtCore.QRect(20, 290, 201, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_4 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 380, 211, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 200, 201, 41))
        self.textEdit_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_6 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_6.setGeometry(QtCore.QRect(20, 550, 211, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.loyality = QtWidgets.QComboBox(self.widget)
        self.loyality.setGeometry(QtCore.QRect(40, 600, 141, 31))
        self.loyality.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 237, 162);")
        self.loyality.setObjectName("loyality")
        self.loyality.addItem("")
        self.loyality.addItem("")
        self.textEdit_7 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_7.setGeometry(QtCore.QRect(20, 160, 201, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_8.setGeometry(QtCore.QRect(20, 470, 211, 41))
        self.textEdit_8.setObjectName("textEdit_8")
        self.overall = QtWidgets.QComboBox(self.widget)
        self.overall.setGeometry(QtCore.QRect(40, 510, 141, 31))
        self.overall.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 237, 162);")
        self.overall.setObjectName("overall")
        self.overall.addItem("")
        self.overall.addItem("")
        self.overall.addItem("")
        self.overall.addItem("")
        self.overall.addItem("")
        self.cart_table = QtWidgets.QTableWidget(Dialog)
        self.cart_table.setGeometry(QtCore.QRect(250, 440, 411, 192))
        self.cart_table.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.cart_table.setObjectName("cart_table")
        self.cart_table.setColumnCount(4)
        self.cart_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table.setHorizontalHeaderItem(3, item)
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(250, 390, 104, 41))
        self.textEdit_2.setStyleSheet("background-color: rgb(100, 13, 153);\n"
"color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.makeorder = QtWidgets.QPushButton(Dialog)
        self.makeorder.setGeometry(QtCore.QRect(710, 580, 211, 51))
        self.makeorder.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.makeorder.setObjectName("makeorder")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(199, -80, 1001, 891))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.city = QtWidgets.QComboBox(self.widget_2)
        self.city.setGeometry(QtCore.QRect(510, 520, 211, 51))
        self.city.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"background-color: rgb(230, 230, 230);")
        self.city.setObjectName("city")
        self.city.addItem("")
        self.city.addItem("")
        self.city.addItem("")
        self.city.addItem("")
        self.city.addItem("")
        self.payment = QtWidgets.QComboBox(self.widget_2)
        self.payment.setGeometry(QtCore.QRect(510, 590, 211, 51))
        self.payment.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(230, 230, 230);")
        self.payment.setObjectName("payment")
        self.payment.addItem("")
        self.payment.addItem("")
        self.payment.addItem("")
        self.payment.addItem("")
        self.subtotal = QtWidgets.QTextEdit(self.widget_2)
        self.subtotal.setGeometry(QtCore.QRect(760, 520, 231, 41))
        self.subtotal.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 208, 255);")
        self.subtotal.setObjectName("subtotal")
        self.tax = QtWidgets.QTextEdit(self.widget_2)
        self.tax.setGeometry(QtCore.QRect(760, 570, 231, 41))
        self.tax.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 208, 255);")
        self.tax.setObjectName("tax")
        self.freight = QtWidgets.QTextEdit(self.widget_2)
        self.freight.setGeometry(QtCore.QRect(760, 620, 231, 41))
        self.freight.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 208, 255);")
        self.freight.setObjectName("freight")
        self.totalamount = QtWidgets.QTextEdit(self.widget_2)
        self.totalamount.setGeometry(QtCore.QRect(760, 670, 231, 41))
        self.totalamount.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(238, 208, 255);")
        self.totalamount.setObjectName("totalamount")
        self.feedback = QtWidgets.QTextEdit(self.widget_2)
        self.feedback.setGeometry(QtCore.QRect(50, 720, 941, 61))
        self.feedback.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(87, 10, 126);")
        self.feedback.setObjectName("feedback")
        self.history = QtWidgets.QPushButton(self.widget_2)
        self.history.setGeometry(QtCore.QRect(810, 120, 181, 41))
        self.history.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.history.setObjectName("history")
        self.widget_2.raise_()
        self.search.raise_()
        self.searchbutt.raise_()
        self.tableWidget.raise_()
        self.widget.raise_()
        self.cart_table.raise_()
        self.textEdit_2.raise_()
        self.makeorder.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.searchbutt.setText(_translate("Dialog", "view products"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "product Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Price"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Subcategory Name"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; color:#ffffff;\">Spring</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; color:#ffffff;\">Store</span></p></body></html>"))
        self.submitrate.setText(_translate("Dialog", "Submit Rate"))
        self.delivery.setItemText(0, _translate("Dialog", "1"))
        self.delivery.setItemText(1, _translate("Dialog", "2"))
        self.delivery.setItemText(2, _translate("Dialog", "3"))
        self.delivery.setItemText(3, _translate("Dialog", "4"))
        self.delivery.setItemText(4, _translate("Dialog", "5"))
        self.quality.setItemText(0, _translate("Dialog", "1"))
        self.quality.setItemText(1, _translate("Dialog", "2"))
        self.quality.setItemText(2, _translate("Dialog", "3"))
        self.quality.setItemText(3, _translate("Dialog", "4"))
        self.quality.setItemText(4, _translate("Dialog", "5"))
        self.service.setItemText(0, _translate("Dialog", "1"))
        self.service.setItemText(1, _translate("Dialog", "2"))
        self.service.setItemText(2, _translate("Dialog", "3"))
        self.service.setItemText(3, _translate("Dialog", "4"))
        self.service.setItemText(4, _translate("Dialog", "5"))
        self.textEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">Product Quality::</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">Customer Service:</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ffffff;\">Delivery Speed:</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ffffff;\">Will You Come Again?</span></p></body></html>"))
        self.loyality.setItemText(0, _translate("Dialog", "yes"))
        self.loyality.setItemText(1, _translate("Dialog", "no"))
        self.textEdit_7.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">Rating</span></p></body></html>"))
        self.textEdit_8.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">Overall Rate:</span></p></body></html>"))
        self.overall.setItemText(0, _translate("Dialog", "1"))
        self.overall.setItemText(1, _translate("Dialog", "2"))
        self.overall.setItemText(2, _translate("Dialog", "3"))
        self.overall.setItemText(3, _translate("Dialog", "4"))
        self.overall.setItemText(4, _translate("Dialog", "5"))
        item = self.cart_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "cart_id"))
        item = self.cart_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "product name"))
        item = self.cart_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "quantity"))
        item = self.cart_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "customer id"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Cart</span></p></body></html>"))
        self.makeorder.setText(_translate("Dialog", "Finish Order"))
        self.city.setItemText(0, _translate("Dialog", "choose city"))
        self.city.setItemText(1, _translate("Dialog", "Mansoura"))
        self.city.setItemText(2, _translate("Dialog", "Cairo"))
        self.city.setItemText(3, _translate("Dialog", "Alex"))
        self.city.setItemText(4, _translate("Dialog", "Aswan"))
        self.payment.setItemText(0, _translate("Dialog", "choose payment method"))
        self.payment.setItemText(1, _translate("Dialog", "Cash"))
        self.payment.setItemText(2, _translate("Dialog", "Online"))
        self.payment.setItemText(3, _translate("Dialog", "Credit"))
        self.subtotal.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Subtotal:</p></body></html>"))
        self.tax.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tax:</p></body></html>"))
        self.freight.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Freight:</p></body></html>"))
        self.totalamount.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total Amount: </p></body></html>"))
        self.feedback.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.history.setText(_translate("Dialog", "View History"))
