# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewhistory.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(40, 190, 1131, 441))
        self.tableWidget.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(430, 100, 341, 51))
        self.textEdit.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.textEdit.setObjectName("textEdit")
        self.backfromhistory = QtWidgets.QPushButton(Dialog)
        self.backfromhistory.setGeometry(QtCore.QRect(40, 90, 161, 61))
        self.backfromhistory.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.backfromhistory.setObjectName("backfromhistory")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "order id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "subtotal"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "total taxes"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "total freight"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "total amount"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "shipping method"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "shipping city"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "payment method"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "order date"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "customer id"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; color:#000000;\">Order History</span></p></body></html>"))
        self.backfromhistory.setText(_translate("Dialog", "Back To Main Page"))
