# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcom_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-570, -190, 1771, 991))
        self.widget.setStyleSheet("background-color: rgb(93, 8, 116);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(1100, 340, 261, 51))
        self.label.setStyleSheet("font: 33pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(980, 400, 461, 51))
        self.label_2.setStyleSheet("font: 23pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.signin = QtWidgets.QPushButton(self.widget)
        self.signin.setGeometry(QtCore.QRect(950, 590, 531, 61))
        self.signin.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(250, 191, 13);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.signin.setObjectName("signin")
        self.create = QtWidgets.QPushButton(self.widget)
        self.create.setGeometry(QtCore.QRect(950, 690, 531, 61))
        self.create.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(250, 191, 13);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.create.setObjectName("create")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome"))
        self.label_2.setText(_translate("Dialog", "Sign in or Create a New Account"))
        self.signin.setText(_translate("Dialog", "Sign in"))
        self.create.setText(_translate("Dialog", "Create New Acoount For Free"))
